spring:
  application:
    name: data-streamer
  datasource:
    url: jdbc:mysql://localhost:3306/uart_sim_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Options: create | update | validate | none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
